/**
 * @file Airplay AirPlay
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'airplay',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                stroke-width={props.strokeWidth}
                fill="none"
                fill-rule="evenodd"
                stroke-linejoin={props.strokeLinejoin}
            >
                <g
                    transform="translate(4.000000, 6.000000)"
                    stroke={props.colors[0]}
                    stroke-width={props.strokeWidth}
                >
                    <path
                        d="M8,29.0136108 L5,29.0136108 L0,29.0136108 L0,2.0126726 C0,0.908621277 0.8954305,0.0136108398 2,0.0136108398 L38,0.0136108398 C39.1045695,0.0136108398 40,0.908621277 40,2.0126726 L40,29.0136108 L32,29.0136108"
                        stroke-linecap={props.strokeLinecap}
                    />
                    <polygon
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        points="20 26 10 36 30 36"
                    />
                </g>
            </g>
        </svg>
    )
);
