/**
 * @file AlignTextBottomOne 文字底对齐1
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'align-text-bottom-one',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                stroke-width={props.strokeWidth}
                fill="none"
                fill-rule="evenodd"
                stroke-linejoin={props.strokeLinejoin}
            >
                <g
                    transform="translate(6.000000, 6.000000)"
                    stroke-width={props.strokeWidth}
                >
                    <rect
                        stroke={props.colors[0]}
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        x="0"
                        y="0"
                        width="36"
                        height="36"
                        rx="3"
                    />
                    <path
                        d="M28,21 L8,21"
                        stroke={props.colors[2]}
                        stroke-linecap={props.strokeLinecap}
                    />
                    <path
                        d="M21,28 L8,28"
                        stroke={props.colors[2]}
                        stroke-linecap={props.strokeLinecap}
                    />
                </g>
            </g>
        </svg>
    )
);
