/**
 * @file ArrowCircleLeft 左-箭头
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'arrow-circle-left',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                stroke-width={props.strokeWidth}
                fill="none"
                fill-rule="evenodd"
            >
                <g>
                    <circle
                        stroke={props.colors[0]}
                        stroke-width={props.strokeWidth}
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        stroke-linejoin={props.strokeLinejoin}
                        cx="24"
                        cy="24"
                        r="20"
                    />
                    <g
                        transform="translate(23.491664, 24.500000) scale(-1, 1) translate(-23.491664, -24.500000) translate(14.491664, 15.000000)"
                        stroke={props.colors[2]}
                        stroke-linecap={props.strokeLinecap}
                        stroke-linejoin={props.strokeLinejoin}
                        stroke-width={props.strokeWidth}
                    >
                        <path
                            d="M0,9.5 L18,9.5"
                        />
                        <polyline
                            points="9 0.5 18 9.5 9 18.5"
                        />
                    </g>
                </g>
            </g>
        </svg>
    )
);
