/**
 * @file Bedside 床头柜
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'bedside',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                stroke-width={props.strokeWidth}
                fill="none"
                fill-rule="evenodd"
                stroke-linejoin={props.strokeLinejoin}
            >
                <g
                    transform="translate(4.000000, 5.000000)"
                    stroke-width={props.strokeWidth}
                >
                    <rect
                        stroke={props.colors[0]}
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        x="0"
                        y="9"
                        width="40"
                        height="12"
                    />
                    <rect
                        stroke={props.colors[0]}
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        x="0"
                        y="21"
                        width="40"
                        height="12"
                    />
                    <path
                        d="M18,15 L22,15"
                        stroke={props.colors[2]}
                        stroke-linecap={props.strokeLinecap}
                    />
                    <path
                        d="M18,27 L22,27"
                        stroke={props.colors[2]}
                        stroke-linecap={props.strokeLinecap}
                    />
                    <path
                        d="M6,33 L6,37"
                        stroke={props.colors[0]}
                        stroke-linecap={props.strokeLinecap}
                    />
                    <path
                        d="M34,33 L34,37"
                        stroke={props.colors[0]}
                        stroke-linecap={props.strokeLinecap}
                    />
                    <path
                        d="M20,9 L20,1"
                        stroke={props.colors[0]}
                        stroke-linecap={props.strokeLinecap}
                        transform="translate(20.000000, 5.000000) rotate(180.000000) translate(-20.000000, -5.000000) "
                    />
                    <path
                        d="M20,7 L20,-5"
                        stroke={props.colors[0]}
                        stroke-linecap={props.strokeLinecap}
                        transform="translate(20.000000, 1.000000) rotate(90.000000) translate(-20.000000, -1.000000) "
                    />
                </g>
            </g>
        </svg>
    )
);
