/**
 * @file BlockOne 俄罗斯方块
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'block-one',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                d="M6 18H18V30H6V18Z"
                fill={props.colors[1]}
            />
            <path
                d="M18 18H30V30H18V18Z"
                fill={props.colors[1]}
            />
            <path
                d="M6 30H18V42H6V30Z"
                fill={props.colors[1]}
            />
            <path
                d="M30 18H42V30H30V18Z"
                fill={props.colors[1]}
            />
            <path
                d="M30 6H42V18H30V6Z"
                fill={props.colors[1]}
            />
            <path
                d="M18 18H6V30M18 18V30M18 18H30M18 30H6M18 30H30M18 30V42H6V30M30 18V30M30 18H42M30 18V6H42V18M30 30H42V18"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
        </svg>
    )
);
