/**
 * @file BlockNine 俄罗斯方块
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'block-nine',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                d="M18 14H30V26H18V14Z"
                fill="#09C8E2"
            />
            <path
                d="M18 14H30V26H18V14Z"
                fill={props.colors[1]}
            />
            <path
                d="M18 14H30V26H18V14Z"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M18 26H30V38H18V26Z"
                fill="#09C8E2"
            />
            <path
                d="M18 26H30V38H18V26Z"
                fill={props.colors[1]}
            />
            <path
                d="M18 26H30V38H18V26Z"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M30 14H42V26H30V14Z"
                fill="#09C8E2"
            />
            <path
                d="M30 14H42V26H30V14Z"
                fill={props.colors[1]}
            />
            <path
                d="M30 14H42V26H30V14Z"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M6 26H18V38H6V26Z"
                fill="#09C8E2"
            />
            <path
                d="M6 26H18V38H6V26Z"
                fill={props.colors[1]}
            />
            <path
                d="M6 26H18V38H6V26Z"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
        </svg>
    )
);
