/**
 * @file BringForward 上层
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'bring-forward',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                stroke-width={props.strokeWidth}
                fill="none"
                fill-rule="evenodd"
            >
                <g>
                    <rect
                        stroke={props.colors[0]}
                        stroke-width={props.strokeWidth}
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        stroke-linejoin={props.strokeLinejoin}
                        x="6"
                        y="34"
                        width="36"
                        height="8"
                    />
                    <rect
                        stroke={props.colors[0]}
                        stroke-width={props.strokeWidth}
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        stroke-linejoin={props.strokeLinejoin}
                        x="6"
                        y="20"
                        width="36"
                        height="8"
                    />
                    <polyline
                        stroke={props.colors[0]}
                        stroke-width={props.strokeWidth}
                        stroke-linecap={props.strokeLinecap}
                        stroke-linejoin={props.strokeLinejoin}
                        transform="translate(24.000000, 9.000000) scale(1, -1) translate(-24.000000, -9.000000) "
                        points="30 6 24 12 18 6 18 6"
                    />
                    <path
                        d="M24,28 L24,34"
                        stroke={props.colors[0]}
                        stroke-width={props.strokeWidth}
                        stroke-linecap={props.strokeLinecap}
                        stroke-linejoin={props.strokeLinejoin}
                    />
                    <path
                        d="M24,6 L24,20"
                        stroke={props.colors[0]}
                        stroke-width={props.strokeWidth}
                        stroke-linecap={props.strokeLinecap}
                        stroke-linejoin={props.strokeLinejoin}
                    />
                </g>
            </g>
        </svg>
    )
);
