/**
 * @file Cell 细胞
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'cell',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                d="M28.4165 21.8466C28.2998 24.4328 28.9576 26.2456 30.3899 27.2852C32.5385 28.8445 37.8372 29.0274 42.0342 21.8466C46.2313 14.6658 42.1598 10.7653 40.6133 10.1148C39.5823 9.68114 38.546 9.51857 37.5044 9.6271"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
            />
            <path
                d="M31.0138 28.0061C29.7932 29.4197 29.6591 31.1176 30.6115 33.1C32.0401 36.0736 35.6988 35.5388 37.5277 38.0158C38.747 39.6671 39.2088 41.3285 38.9132 43"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
            />
            <path
                fill-rule="evenodd"
                clip-rule="evenodd"
                d="M8.50434 23.6397C10.7641 26.661 16.1663 27.0552 22.5 24.6307C25.0645 23.649 27.7817 22.2053 30.5049 20.2867C32.5577 18.8405 34.0451 17.3644 35.0919 15.92C38.8633 10.7161 36.9159 5.92228 35.0919 4.40641C33.1156 2.76405 29.322 2.08894 22.5 5.03351C21.2777 5.56109 19.9582 6.20487 18.5345 6.98011C15.7374 8.50319 13.4336 10.2233 11.6622 12C7.4997 16.1749 6.27733 20.6623 8.50434 23.6397Z"
                fill={props.colors[1]}
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
            />
            <path
                d="M16.2451 8.83917C16.6842 11.789 17.9165 14.3681 19.9419 16.5765C21.9673 18.7849 24.3883 20.1951 28 21.5"
                stroke={props.colors[2]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
            />
            <path
                d="M9.98149 24.9998C4.15571 30.6503 2.58552 34.9286 5.27092 37.8347C9.29902 42.1937 13.0878 36.6267 18.1666 36.6267C21.5524 36.6267 24.1636 38.7511 26 42.9998"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
            />
            <path
                d="M35.0919 15.92C34.0451 17.3644 32.5577 18.8404 30.5049 20.2867C27.7817 22.2053 25.0645 23.649 22.5 24.6307"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
            />
            <path
                d="M22.4999 5.03351C21.2776 5.56109 19.9581 6.20487 18.5344 6.9801C15.7374 8.50318 13.4335 10.2233 11.6621 12"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
            />
        </svg>
    )
);
