/**
 * @file Certificate 证书
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'certificate',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                d="M36 27C36 28.777 35.2275 30.3736 34 31.4722C32.9385 32.4223 31.5367 33 30 33C28.4633 33 27.0615 32.4223 26 31.4722C24.7725 30.3736 24 28.777 24 27C24 23.6863 26.6863 21 30 21C33.3137 21 36 23.6863 36 27Z"
                fill={props.colors[1]}
            />
            <path
                d="M44 6H4V36H26V31.4722C24.7725 30.3736 24 28.777 24 27C24 23.6863 26.6863 21 30 21C33.3137 21 36 23.6863 36 27C36 28.777 35.2275 30.3736 34 31.4722V36H44V6Z"
                fill={props.colors[1]}
            />
            <path
                d="M30 40L34 42V36V31.4722C32.9385 32.4223 31.5367 33 30 33C28.4633 33 27.0615 32.4223 26 31.4722V36V42L30 40Z"
                fill={props.colors[1]}
            />
            <path
                d="M26 36H4V6H44V36H34M26 36V31.4722M26 36V42M34 36V31.4722M34 36V42M34 42L30 40L26 42M34 42V31.4722M26 42V31.4722M34 31.4722C35.2275 30.3736 36 28.777 36 27C36 23.6863 33.3137 21 30 21C26.6863 21 24 23.6863 24 27C24 28.777 24.7725 30.3736 26 31.4722M34 31.4722C32.9385 32.4223 31.5367 33 30 33C28.4633 33 27.0615 32.4223 26 31.4722"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M12 14L36 14"
                stroke={props.colors[2]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M12 21H18"
                stroke={props.colors[2]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M12 28H16"
                stroke={props.colors[2]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
        </svg>
    )
);
