/**
 * @file Comment 评论
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'comment',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                fill-rule="evenodd"
                clip-rule="evenodd"
                d="M6 6C4.89543 6 4 6.89543 4 8V34C4 35.1046 4.89543 36 6 36H12V42L22 36H42C43.1046 36 44 35.1046 44 34V8C44 6.89543 43.1046 6 42 6H6Z"
                fill={props.colors[1]}
            />
            <path
                d="M12 36H14C14 34.8954 13.1046 34 12 34V36ZM12 42H10C10 42.7205 10.3876 43.3854 11.0146 43.7404C11.6416 44.0954 12.4111 44.0857 13.029 43.715L12 42ZM22 36V34C21.6375 34 21.2818 34.0985 20.971 34.285L22 36ZM6 8V8V4C3.79086 4 2 5.79086 2 8H6ZM6 34V8H2V34H6ZM6 34H6H2C2 36.2091 3.79086 38 6 38V34ZM12 34H6V38H12V34ZM10 36V42H14V36H10ZM13.029 43.715L23.029 37.715L20.971 34.285L10.971 40.285L13.029 43.715ZM42 34H22V38H42V34ZM42 34V38C44.2091 38 46 36.2091 46 34H42ZM42 8V34H46V8H42ZM42 8H46C46 5.79086 44.2091 4 42 4V8ZM6 8H42V4H6V8Z"
                fill={props.colors[0]}
            />
            <path
                d="M14 19.5V22.5"
                stroke={props.colors[2]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M24 19.5V22.5"
                stroke={props.colors[2]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M34 19.5V22.5"
                stroke={props.colors[2]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
        </svg>
    )
);
