/**
 * @file Flask 三角杯
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'flask',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                stroke-width={props.strokeWidth}
                fill="none"
                fill-rule="evenodd"
            >
                <g>
                    <polygon
                        stroke={props.colors[0]}
                        stroke-width={props.strokeWidth}
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        stroke-linejoin={props.strokeLinejoin}
                        points="37.8449774 35.0219317 44 41.3157895 44 44 4 44 4 41.3157895 10.1183816 35.0593993"
                    />
                    <polyline
                        stroke={props.colors[0]}
                        stroke-width={props.strokeWidth}
                        stroke-linecap={props.strokeLinecap}
                        stroke-linejoin={props.strokeLinejoin}
                        points="10.1038429 35.074266 18 27 18 6 18 6 30 6 30 27 37.8725898 35.050167"
                    />
                    <path
                        d="M11,35 L37,35"
                        stroke={props.colors[0]}
                        stroke-width={props.strokeWidth}
                        stroke-linecap={props.strokeLinecap}
                        stroke-linejoin={props.strokeLinejoin}
                    />
                    <path
                        d="M30,14 L24,14"
                        stroke={props.colors[0]}
                        stroke-width={props.strokeWidth}
                        stroke-linecap={props.strokeLinecap}
                        stroke-linejoin={props.strokeLinejoin}
                    />
                    <path
                        d="M30,20 L24,20"
                        stroke={props.colors[0]}
                        stroke-width={props.strokeWidth}
                        stroke-linecap={props.strokeLinecap}
                        stroke-linejoin={props.strokeLinejoin}
                    />
                </g>
            </g>
        </svg>
    )
);
