/**
 * @file MallBag 购物袋
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'mall-bag',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                stroke-width={props.strokeWidth}
                fill="none"
                fill-rule="evenodd"
            >
                <g
                    transform="translate(6.000000, 5.000000)"
                    stroke-linejoin={props.strokeLinejoin}
                    stroke-width={props.strokeWidth}
                >
                    <path
                        d="M0,7.6 L0,36 C0,37.1045695 0.8954305,38 2,38 L34,38 C35.1045695,38 36,37.1045695 36,36 L36,7.6 L0,7.6 Z"
                        stroke={props.colors[0]}
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                    />
                    <polyline
                        stroke={props.colors[0]}
                        stroke-linecap={props.strokeLinecap}
                        points="36 7.6 30.3333333 2.13162821e-14 5.66666667 2.13162821e-14 1.38555833e-13 7.6 1.38555833e-13 7.6"
                    />
                    <path
                        d="M25.5555556,14.2 C25.5555556,18.3973641 22.1728181,21.8 18,21.8 C13.8271819,21.8 10.4444444,18.3973641 10.4444444,14.2"
                        stroke={props.colors[2]}
                        stroke-linecap={props.strokeLinecap}
                    />
                </g>
            </g>
        </svg>
    )
);
