/**
 * @file MicroscopeOne 显微镜
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'microscope-one',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                d="M9.17208 22.8497C9.11629 22.7939 9.11629 22.7035 9.17208 22.6477L22.8596 8.96014C25.0075 6.81225 28.4899 6.81225 30.6378 8.96014C32.7857 11.108 32.7857 14.5904 30.6378 16.7383L16.9502 30.4259C16.8945 30.4817 16.804 30.4817 16.7482 30.4259L9.17208 22.8497Z"
                fill={props.colors[1]}
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
            />
            <path
                d="M28.1629 6.48526L29.9307 4.71749C31.2975 3.35066 33.5136 3.35066 34.8804 4.71749C36.2473 6.08433 36.2473 8.30041 34.8804 9.66724L33.1127 11.435L28.1629 6.48526Z"
                fill={props.colors[1]}
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M10.4853 24.1629L6.24262 28.4056L11.1924 33.3553L15.435 29.1127L10.4853 24.1629Z"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <circle
                cx="26.0416"
                cy="22.0416"
                r="4.5"
                transform="rotate(45 26.0416 22.0416)"
                fill={props.colors[1]}
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
            />
            <path
                d="M7.65684 18.5061C6.87579 17.725 5.60947 17.725 4.82842 18.5061C4.04737 19.2871 4.04737 20.5535 4.82842 21.3345L7.65684 18.5061ZM18.2634 34.7695C19.0445 35.5506 20.3108 35.5506 21.0919 34.7695C21.8729 33.9885 21.8729 32.7222 21.0919 31.9411L18.2634 34.7695ZM4.82842 21.3345L18.2634 34.7695L21.0919 31.9411L7.65684 18.5061L4.82842 21.3345Z"
                fill={props.colors[0]}
            />
            <path
                d="M10 44H42"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M31 22C35 22 39 26 39 32C39 38.4 33.8333 41.8333 31 44"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
        </svg>
    )
);
