/**
 * @file PersonalPrivacy 个人隐私
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'personal-privacy',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <circle
                cx="24"
                cy="11"
                r="7"
                fill={props.colors[1]}
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M4 41C4 32.1634 12.0589 25 22 25"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <rect
                x="27"
                y="31"
                width="14"
                height="10"
                fill={props.colors[1]}
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M37 31V28C37 26.3431 35.6569 25 34 25C32.3431 25 31 26.3431 31 28V31"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
        </svg>
    )
);
