/**
 * @file ShieldAdd 安全增加
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'shield-add',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                stroke-width={props.strokeWidth}
                fill="none"
                fill-rule="evenodd"
            >
                <g>
                    <path
                        d="M6,8.25564385 L24.008642,3 L42,8.25564385 L42,19.0336798 C42,30.3621834 34.7502223,40.4194233 24.0026245,44.0005035 L24.0026245,44.0005035 C13.2520792,40.4194856 6,30.3599802 6,19.0286999 L6,8.25564385 Z"
                        stroke={props.colors[0]}
                        stroke-width={props.strokeWidth}
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        stroke-linejoin={props.strokeLinejoin}
                    />
                    <path
                        d="M18.2928932,17.2928932 L29.6066017,28.6066017"
                        stroke={props.colors[2]}
                        stroke-width={props.strokeWidth}
                        stroke-linecap={props.strokeLinecap}
                        stroke-linejoin={props.strokeLinejoin}
                        transform="translate(23.949747, 22.949747) rotate(45.000000) translate(-23.949747, -22.949747) "
                    />
                    <path
                        d="M29.6066017,17.2928932 L18.2928932,28.6066017"
                        stroke={props.colors[2]}
                        stroke-width={props.strokeWidth}
                        stroke-linecap={props.strokeLinecap}
                        stroke-linejoin={props.strokeLinejoin}
                        transform="translate(23.949747, 22.949747) rotate(-135.000000) translate(-23.949747, -22.949747) "
                    />
                </g>
            </g>
        </svg>
    )
);
