/**
 * @file Ungroup 解组
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'ungroup',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                stroke-width={props.strokeWidth}
                fill="none"
                fill-rule="evenodd"
                stroke-linejoin={props.strokeLinejoin}
            >
                <g
                    transform="translate(4.000000, 4.000000)"
                    stroke={props.colors[0]}
                    stroke-width={props.strokeWidth}
                >
                    <rect
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        x="0"
                        y="0"
                        width="7.27272727"
                        height="7.27272727"
                    />
                    <rect
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        x="32.7272727"
                        y="32.7272727"
                        width="7.27272727"
                        height="7.27272727"
                    />
                    <rect
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        x="0"
                        y="20"
                        width="7.27272727"
                        height="7.27272727"
                    />
                    <rect
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        x="12.7272727"
                        y="32.7272727"
                        width="7.27272727"
                        height="7.27272727"
                    />
                    <rect
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        x="20"
                        y="0"
                        width="7.27272727"
                        height="7.27272727"
                    />
                    <rect
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        x="32.7272727"
                        y="12.7272727"
                        width="7.27272727"
                        height="7.27272727"
                    />
                    <path
                        d="M7.27272727,3.63636364 L20,3.63636364"
                        stroke-linecap={props.strokeLinecap}
                    />
                    <path
                        d="M20,36.3636364 L32.7272727,36.3636364"
                        stroke-linecap={props.strokeLinecap}
                    />
                    <polyline
                        stroke-linecap={props.strokeLinecap}
                        points="7.27272727 23.6363636 23.6363636 23.6363636 23.6363636 7.27272727"
                    />
                    <path
                        d="M16.3636364,32.7272727 L16.3636364,23.6286016 M24.8278628,16.3636364 L32.7272727,16.3636364"
                        stroke-linecap={props.strokeLinecap}
                    />
                    <path
                        d="M3.63636364,7.27272727 L3.63636364,20"
                        stroke-linecap={props.strokeLinecap}
                    />
                    <path
                        d="M36.3636364,20 L36.3636364,32.7272727"
                        stroke-linecap={props.strokeLinecap}
                    />
                </g>
            </g>
        </svg>
    )
);
