/**
 * @file Voicemail 语音信息
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'voicemail',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                stroke-width={props.strokeWidth}
                fill="none"
                fill-rule="evenodd"
                stroke-linejoin={props.strokeLinejoin}
            >
                <g
                    transform="translate(4.000000, 17.000000)"
                    stroke={props.colors[0]}
                    stroke-width={props.strokeWidth}
                >
                    <circle
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        cx="7"
                        cy="7"
                        r="7"
                    />
                    <circle
                        fill={props.colors[1]}
                        fill-rule="nonzero"
                        cx="33"
                        cy="7"
                        r="7"
                    />
                    <path
                        d="M8,14 L32,14"
                        stroke-linecap={props.strokeLinecap}
                    />
                </g>
            </g>
        </svg>
    )
);
