/**
 * @file VrGlasses VR 眼镜
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'vr-glasses',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                fill-rule="evenodd"
                clip-rule="evenodd"
                d="M2 12H46V36H30L24 30L18 36H2V12Z"
                fill="#09C8E2"
            />
            <path
                fill-rule="evenodd"
                clip-rule="evenodd"
                d="M2 12H46V36H30L24 30L18 36H2V12Z"
                fill={props.colors[1]}
            />
            <path
                fill-rule="evenodd"
                clip-rule="evenodd"
                d="M2 12H46V36H30L24 30L18 36H2V12Z"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                fill-rule="evenodd"
                clip-rule="evenodd"
                d="M13 28C15.2091 28 17 26.2091 17 24C17 21.7909 15.2091 20 13 20C10.7909 20 9 21.7909 9 24C9 26.2091 10.7909 28 13 28Z"
                fill={props.colors[3]}
                stroke={props.colors[2]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                fill-rule="evenodd"
                clip-rule="evenodd"
                d="M35 28C37.2091 28 39 26.2091 39 24C39 21.7909 37.2091 20 35 20C32.7909 20 31 21.7909 31 24C31 26.2091 32.7909 28 35 28Z"
                fill={props.colors[3]}
                stroke={props.colors[2]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
        </svg>
    )
);
