/**
 * @file ACane 手杖
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper(
    'a-cane',
    true,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <g
                clipPath={'url(#' + props.id + 'e7be1e38' + ')'}
            >
                <path
                    d="M17.4113 7.87324C16.8713 8.8368 17.2147 10.0557 18.1782 10.5957C19.1418 11.1357 20.3607 10.7924 20.9007 9.82885L17.4113 7.87324ZM17.9574 43.716C17.4174 44.6795 17.7608 45.8984 18.7243 46.4385C19.6879 46.9785 20.9068 46.6351 21.4468 45.6716L17.9574 43.716ZM20.9007 9.82885C22.7908 6.4564 27.0569 5.25471 30.4294 7.1448L32.385 3.65545C27.0854 0.6853 20.3815 2.57367 17.4113 7.87324L20.9007 9.82885ZM30.4294 7.1448C33.8018 9.0349 35.0035 13.301 33.1134 16.6735L36.6028 18.6291C39.5729 13.3295 37.6846 6.6256 32.385 3.65545L30.4294 7.1448ZM33.1134 16.6735L17.9574 43.716L21.4468 45.6716L36.6028 18.6291L33.1134 16.6735Z"
                    fill={props.colors[0]}
                />
            </g>
            <defs>
                <clipPath
                    id={props.id + 'e7be1e38'}
                >
                    <rect
                        width="48"
                        height="48"
                        fill={props.colors[2]}
                    />
                </clipPath>
            </defs>
        </svg>
    )
);
