/**
 * @file AlignTextTop 文字顶对齐
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper(
    'align-text-top',
    true,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                strokeWidth={props.strokeWidth}
                fill="none"
                fillRule="evenodd"
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
            >
                <g
                    transform="translate(6.000000, 6.000000)"
                    stroke={props.colors[0]}
                    strokeWidth={props.strokeWidth}
                >
                    <path
                        d="M0,30.3055556 L36,30.3055556"
                    />
                    <path
                        d="M0,36 L36,36"
                    />
                    <polyline
                        transform="translate(18.000000, 3.000000) scale(1, -1) translate(-18.000000, -3.000000) "
                        points="24 0 18 6 12 0 12 0"
                    />
                    <path
                        d="M18,0 L18,23"
                    />
                </g>
            </g>
        </svg>
    )
);
