/**
 * @file BlockSeven 俄罗斯方块
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper(
    'block-seven',
    true,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                d="M18 18H30V30H18V18Z"
                fill="#09C8E2"
            />
            <path
                d="M18 18H30V30H18V18Z"
                fill={props.colors[1]}
            />
            <path
                d="M18 18H30V30H18V18Z"
                stroke={props.colors[0]}
                strokeWidth={props.strokeWidth}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
            />
            <path
                d="M30 18H42V30H30V18Z"
                fill="#09C8E2"
            />
            <path
                d="M30 18H42V30H30V18Z"
                fill={props.colors[1]}
            />
            <path
                d="M30 18H42V30H30V18Z"
                stroke={props.colors[0]}
                strokeWidth={props.strokeWidth}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
            />
            <path
                d="M6 18H18V30H6V18Z"
                fill="#09C8E2"
            />
            <path
                d="M6 18H18V30H6V18Z"
                fill={props.colors[1]}
            />
            <path
                d="M6 18H18V30H6V18Z"
                stroke={props.colors[0]}
                strokeWidth={props.strokeWidth}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
            />
            <path
                d="M18 30H30V42H18V30Z"
                fill="#09C8E2"
            />
            <path
                d="M18 30H30V42H18V30Z"
                fill={props.colors[1]}
            />
            <path
                d="M18 30H30V42H18V30Z"
                stroke={props.colors[0]}
                strokeWidth={props.strokeWidth}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
            />
            <path
                d="M18 6H30V18H18V6Z"
                fill="#09C8E2"
            />
            <path
                d="M18 6H30V18H18V6Z"
                fill={props.colors[1]}
            />
            <path
                d="M18 6H30V18H18V6Z"
                stroke={props.colors[0]}
                strokeWidth={props.strokeWidth}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
            />
        </svg>
    )
);
