/**
 * @file BrowserChrome 浏览器-chrome
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper(
    'browser-chrome',
    true,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                strokeWidth={props.strokeWidth}
                fill="none"
                fillRule="evenodd"
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
            >
                <g
                    transform="translate(4.000000, 4.000000)"
                    stroke={props.colors[0]}
                    strokeWidth={props.strokeWidth}
                >
                    <circle
                        cx="20"
                        cy="20"
                        r="20"
                    />
                    <circle
                        cx="20"
                        cy="20"
                        r="9"
                    />
                    <path
                        d="M20,11 L37,11"
                    />
                    <path
                        d="M13.6438981,38 L25.6438981,27"
                    />
                    <path
                        d="M2.87508068,12.5520382 L12.8750807,25.5520382"
                    />
                </g>
            </g>
        </svg>
    )
);
