/**
 * @file Play 播放
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper(
    'play',
    true,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                strokeWidth={props.strokeWidth}
                fill="none"
                fillRule="evenodd"
            >
                <g>
                    <circle
                        stroke={props.colors[0]}
                        strokeWidth={props.strokeWidth}
                        fill={props.colors[1]}
                        fillRule="nonzero"
                        strokeLinejoin={props.strokeLinejoin}
                        cx="24"
                        cy="24"
                        r="20"
                    />
                    <polygon
                        stroke={props.colors[2]}
                        strokeWidth={props.strokeWidth}
                        fill={props.colors[3]}
                        fillRule="nonzero"
                        strokeLinejoin={props.strokeLinejoin}
                        transform="translate(24.000000, 24.000000) rotate(90.000000) translate(-24.000000, -24.000000) "
                        points="24 28 17.0717968 28 20.5358984 22 24 16 27.4641016 22 30.9282032 28"
                    />
                </g>
            </g>
        </svg>
    )
);
