/**
 * @file Search 搜索
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper(
    'search',
    true,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                strokeWidth={props.strokeWidth}
                fill="none"
                fillRule="evenodd"
            >
                <g>
                    <circle
                        stroke={props.colors[0]}
                        strokeWidth={props.strokeWidth}
                        fill={props.colors[1]}
                        fillRule="nonzero"
                        strokeLinejoin={props.strokeLinejoin}
                        cx="21"
                        cy="21"
                        r="17"
                    />
                    <path
                        d="M26.6568542,14.3431458 C25.209139,12.8954305 23.209139,12 21,12 C18.790861,12 16.790861,12.8954305 15.3431458,14.3431458"
                        stroke={props.colors[2]}
                        strokeWidth={props.strokeWidth}
                        strokeLinecap={props.strokeLinecap}
                        strokeLinejoin={props.strokeLinejoin}
                    />
                    <path
                        d="M31.4644661,37.4644661 L43.4644661,37.4644661"
                        stroke={props.colors[0]}
                        strokeWidth={props.strokeWidth}
                        strokeLinecap={props.strokeLinecap}
                        strokeLinejoin={props.strokeLinejoin}
                        transform="translate(37.464466, 37.464466) rotate(45.000000) translate(-37.464466, -37.464466) "
                    />
                </g>
            </g>
        </svg>
    )
);
