/**
 * @file SteeringWheel 方向盘
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper(
    'steering-wheel',
    true,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                d="M32 24C32 28.4183 28.4183 32 24 32C19.5817 32 16 28.4183 16 24C16 19.5817 19.5817 16 24 16C28.4183 16 32 19.5817 32 24Z"
                fill={props.colors[1]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M32 24C32 28.4183 28.4183 32 24 32C19.5817 32 16 28.4183 16 24C16 19.5817 19.5817 16 24 16C28.4183 16 32 19.5817 32 24Z"
                fill={props.colors[1]}
            />
            <path
                d="M44 24C44 35.0457 35.0457 44 24 44M44 24C44 12.9543 35.0457 4 24 4C12.9543 4 4 12.9543 4 24M44 24H32M24 44C12.9543 44 4 35.0457 4 24M24 44V32M4 24H16M32 24C32 28.4183 28.4183 32 24 32M32 24C32 19.5817 28.4183 16 24 16C19.5817 16 16 19.5817 16 24M24 32C19.5817 32 16 28.4183 16 24"
                stroke={props.colors[0]}
                strokeWidth={props.strokeWidth}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
            />
        </svg>
    )
);
