/**
 * @file Switch 切换
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper(
    'switch',
    true,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
        >
            <g
                stroke="none"
                strokeWidth={props.strokeWidth}
                fill="none"
                fillRule="evenodd"
            >
                <g>
                    <g
                        transform="translate(5.899495, 7.000000)"
                        stroke={props.colors[0]}
                        strokeLinecap={props.strokeLinecap}
                        strokeLinejoin={props.strokeLinejoin}
                        strokeWidth={props.strokeWidth}
                    >
                        <g>
                            <path
                                d="M36.1005051,12 L0.100505063,12"
                            />
                            <path
                                d="M24.1005051,0 L36.1005051,12"
                            />
                        </g>
                        <g
                            transform="translate(18.500000, 27.000000) scale(-1, 1) translate(-18.500000, -27.000000) translate(0.000000, 20.000000)"
                        >
                            <path
                                d="M36.1005051,2 L0.100505063,2"
                            />
                            <path
                                d="M36.1005051,2 L24.1005051,14"
                            />
                        </g>
                    </g>
                </g>
            </g>
        </svg>
    )
);
