/**
 * @file Butterfly 蝴蝶
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper(
    'butterfly',
    false,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                d="M4.99996 12.0003C8.66364 7.70613 19.0812 18.8191 24 25C28.9188 18.8191 39.3363 7.70599 43 12.0001C43.6785 12.6507 44.4425 14.877 42 18C41.3214 18.9759 40.1857 21.7059 41 26C41 27.1386 39.8849 28.9519 35 27C37.3746 28.6266 41.8495 33.0962 39 37C36.2862 40.4158 29.9646 44.4569 26 35L24 31L22 35C18.0354 44.4569 11.7138 40.4158 9 37C6.15047 33.0962 10.6253 28.6268 12.9999 27.0003C8.11495 28.9521 6.99987 27.1389 6.99987 26.0003C7.81413 21.7061 6.67843 18.9762 5.99988 18.0003C3.55742 14.8773 4.3215 12.6509 4.99996 12.0003Z"
                fill={props.colors[1]}
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M24.0322 23C23.534 17.8642 28.9135 7 33 7"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M23.9678 23C24.466 17.8642 19.0865 7 15 7"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
        </svg>
    )
);
