/**
 * @file Comments 评论
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper(
    'comments',
    true,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                d="M33 38H22V30H36V22H44V38H39L36 41L33 38Z"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M4 6H36V30H17L13 34L9 30H4V6Z"
                fill={props.colors[1]}
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M12 22H18"
                stroke={props.colors[2]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
            />
            <path
                d="M12 14H24"
                stroke={props.colors[2]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
            />
        </svg>
    )
);
