/**
 * @file FileSettingsOne 文件设置1
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper(
    'file-settings-one',
    true,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                d="M40 23V14L31 4H10C8.89543 4 8 4.89543 8 6V42C8 43.1046 8.89543 44 10 44H22"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <circle
                cx="34"
                cy="36"
                r="5"
                fill={props.colors[1]}
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
            />
            <path
                d="M34 28V31"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M34 41V44"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M39.8281 30L37.7068 32.1213"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M29.8281 40L27.7068 42.1213"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M28 30L30.1213 32.1213"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M38 40L40.1213 42.1213"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M26 36H27.5H29"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M39 36H40.5H42"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M30 4V14H40"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
        </svg>
    )
);
