/**
 * @file ZoomInternal 缩放
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper(
    'zoom-internal',
    true,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                d="M44 4H4V44H44V4Z"
                fill={props.colors[1]}
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M16 4V16H4"
                stroke={props.colors[2]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M36 24V36H24"
                stroke={props.colors[2]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M36 36L24 24"
                stroke={props.colors[2]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M4 6V26"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
            <path
                d="M7 4H27"
                stroke={props.colors[0]}
                stroke-width={props.strokeWidth}
                stroke-linecap={props.strokeLinecap}
                stroke-linejoin={props.strokeLinejoin}
            />
        </svg>
    )
);
