/**
 * @file More 更多
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper('more', (props: ISvgIconProps) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
    + '<svg width="' + props.size + '" height="' + props.size + '" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
        + '<circle cx="12" cy="24" r="3" fill="' + props.colors[0] + '"/>'
        + '<circle cx="24" cy="24" r="3" fill="' + props.colors[0] + '"/>'
        + '<circle cx="36" cy="24" r="3" fill="' + props.colors[0] + '"/>'
    + '</svg>'
));
