/**
 * @file Pad 平板电脑
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper('pad', (props: ISvgIconProps) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
    + '<svg width="' + props.size + '" height="' + props.size + '" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">'
        + '<g>'
            + '<g>'
                + '<rect fill-opacity="0.01" fill="#FFFFFF" x="0" y="0" width="48" height="48" stroke-width="' + props.strokeWidth + '" stroke="none" fill-rule="evenodd"/>'
                + '<g transform="translate(6.000000, 4.000000)">'
                    + '<rect stroke="' + props.colors[0] + '" stroke-width="' + props.strokeWidth + '" fill="' + props.colors[1] + '" fill-rule="nonzero" stroke-linejoin="' + props.strokeLinejoin + '" x="0" y="0" width="36" height="27"/>'
                    + '<polyline stroke="' + props.colors[0] + '" stroke-width="' + props.strokeWidth + '" stroke-linecap="' + props.strokeLinecap + '" stroke-linejoin="' + props.strokeLinejoin + '" points="36 27 36 40 0 40 0 27 0 27" fill="none" fill-rule="evenodd"/>'
                    + '<rect fill="' + props.colors[2] + '" x="6" y="5" width="5" height="5" rx="1" stroke-width="' + props.strokeWidth + '" stroke="none" fill-rule="evenodd"/>'
                    + '<rect fill="' + props.colors[2] + '" x="6" y="12" width="5" height="5" rx="1" stroke-width="' + props.strokeWidth + '" stroke="none" fill-rule="evenodd"/>'
                    + '<rect fill="' + props.colors[2] + '" x="15.5" y="5" width="5" height="5" rx="1" stroke-width="' + props.strokeWidth + '" stroke="none" fill-rule="evenodd"/>'
                    + '<rect fill="' + props.colors[2] + '" x="15.5" y="12" width="5" height="5" rx="1" stroke-width="' + props.strokeWidth + '" stroke="none" fill-rule="evenodd"/>'
                    + '<rect fill="' + props.colors[0] + '" x="15.5" y="31" width="5" height="5" rx="2.5" stroke-width="' + props.strokeWidth + '" stroke="none" fill-rule="evenodd"/>'
                    + '<rect fill="' + props.colors[2] + '" x="25" y="5" width="5" height="5" rx="1" stroke-width="' + props.strokeWidth + '" stroke="none" fill-rule="evenodd"/>'
                + '</g>'
            + '</g>'
        + '</g>'
    + '</svg>'
));
