/**
 * @file Redo 重新
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper('redo', (props: ISvgIconProps) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
    + '<svg width="' + props.size + '" height="' + props.size + '" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">'
        + '<g>'
            + '<g>'
                + '<rect fill-opacity="0.01" fill="#FFFFFF" x="0" y="0" width="48" height="48" stroke-width="' + props.strokeWidth + '" stroke="none" fill-rule="evenodd"/>'
                + '<g transform="translate(24.000000, 24.000000) scale(-1, 1) translate(-24.000000, -24.000000) translate(6.000000, 6.000000)">'
                    + '<path d="M5.27207794,30.7279221 C8.52943725,33.9852814 13.0294373,36 18,36 C27.9411255,36 36,27.9411255 36,18 C36,8.0588745 27.9411255,7.10542736e-15 18,7.10542736e-15 C13.0294373,7.10542736e-15 8.52943725,2.01471863 5.27207794,5.27207794 C4.16674151,6.37741436 2.4093822,8.28672172 1.0658141e-14,11" stroke-linecap="' + props.strokeLinecap + '" stroke-linejoin="' + props.strokeLinejoin + '" stroke-width="' + props.strokeWidth + '" stroke="' + props.colors[0] + '" fill="none" fill-rule="evenodd"/>'
                    + '<polyline points="8.8817842e-16 2 8.8817842e-16 11 9 11" stroke-linecap="' + props.strokeLinecap + '" stroke-linejoin="' + props.strokeLinejoin + '" stroke-width="' + props.strokeWidth + '" stroke="' + props.colors[0] + '" fill="none" fill-rule="evenodd"/>'
                + '</g>'
            + '</g>'
        + '</g>'
    + '</svg>'
));
