/**
 * @file TextUnderline 文字下划线
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper('text-underline', (props: ISvgIconProps) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
    + '<svg width="' + props.size + '" height="' + props.size + '" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">'
        + '<g>'
            + '<g transform="translate(8.000000, 6.096979)">'
                + '<path d="M0,37.9030211 L32,37.9030211" stroke-linejoin="' + props.strokeLinejoin + '" stroke-linecap="' + props.strokeLinecap + '" stroke-width="' + props.strokeWidth + '" stroke="' + props.colors[0] + '" fill="none" fill-rule="evenodd"/>'
                + '<path d="M29,-1.0658141e-13 C29,6.66666667 29,9.2363544 29,15.9030211 C29,23.0827228 23.1797017,28.9030211 16,28.9030211 C8.82029825,28.9030211 3,23.0827228 3,15.9030211 C3,9.2363544 3,6.66666667 3,-1.0658141e-13" stroke-linecap="' + props.strokeLinecap + '" stroke-width="' + props.strokeWidth + '" stroke="' + props.colors[0] + '" fill="none" fill-rule="evenodd"/>'
            + '</g>'
        + '</g>'
    + '</svg>'
));
