/**
 * @file UploadThree 上传3
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconWrapper} from '../runtime';

export default IconWrapper('upload-three', (props: ISvgIconProps) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
    + '<svg width="' + props.size + '" height="' + props.size + '" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">'
        + '<g>'
            + '<g>'
                + '<rect fill-opacity="0.01" fill="#FFFFFF" x="0" y="0" width="48" height="48" stroke-width="' + props.strokeWidth + '" stroke="none" fill-rule="evenodd"/>'
                + '<rect stroke="' + props.colors[0] + '" stroke-width="' + props.strokeWidth + '" fill="' + props.colors[1] + '" fill-rule="nonzero" stroke-linejoin="' + props.strokeLinejoin + '" x="6" y="6" width="36" height="36" rx="3"/>'
                + '<g transform="translate(24.000000, 28.000000) scale(1, -1) translate(-24.000000, -28.000000) translate(16.000000, 20.000000)">'
                    + '<polyline transform="translate(8.000000, 12.000000) rotate(90.000000) translate(-8.000000, -12.000000) " points="4 4 12 12 4 20" stroke-linecap="' + props.strokeLinecap + '" stroke-linejoin="' + props.strokeLinejoin + '" stroke-width="' + props.strokeWidth + '" stroke="' + props.colors[2] + '" fill="none" fill-rule="evenodd"/>'
                    + '<path d="M0.25,7.75 L15.75,7.75" transform="translate(8.000000, 7.750000) rotate(90.000000) translate(-8.000000, -7.750000) " stroke-linecap="' + props.strokeLinecap + '" stroke-linejoin="' + props.strokeLinejoin + '" stroke-width="' + props.strokeWidth + '" stroke="' + props.colors[2] + '" fill="none" fill-rule="evenodd"/>'
                + '</g>'
                + '<path d="M16,14 L32,14" stroke="' + props.colors[2] + '" stroke-width="' + props.strokeWidth + '" stroke-linecap="' + props.strokeLinecap + '" stroke-linejoin="' + props.strokeLinejoin + '" fill="none" fill-rule="evenodd"/>'
            + '</g>'
        + '</g>'
    + '</svg>'
));
